[package]
name = "gameboy"
version = "0.1.0"
edition = "2018"

[dependencies]
rand = "0.8.4"
clap = "3.0.0-beta.2"
glium = "0.29.0"
imgui = "0.7.0"
imgui-winit-support = "0.7.1"
imgui-glium-renderer = "0.7.0"
thiserror = "1.0.26"
anyhow = "1.0.41"
